baseURL: "https://apurvakhatri.com/"
title: Apurva Khatri
pagerSize: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-0FQ71EX984

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production
  title: Apurva Khatri
  description: "Apurva Khatri's portfolio website"
  keywords: [Blog, Portfolio, PaperMod]
  author: Apurva Khatri
  DateFormat: "January 2, 2006"
  defaultTheme: light #auto # dark # light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  ShowWordCount: true
  ShowRssButtonInSectionTermList: true
  UseHugoToc: true
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  social:
    twitter: "your_twitter_handle"
    facebook_admin: "your_facebook_admin_id"
    images:
      - "https://apurvakhatri.com/images/sample.jpg" # Example image

  socialIcons:
      - name: github
        url: "https://github.com/apurvakhatri"
      - name: linkedin
        url: "https://www.linkedin.com/in/apurvakhatri/"

  assets:
    favicon: "<link / abs url>"
    favicon16x16: "<link / abs url>"
    favicon32x32: "<link / abs url>"
    apple_touch_icon: "<link / abs url>"
    safari_pinned_tab: "<link / abs url>"

  label:
    text: "Apurva Khatri"

  profileMode:
    enabled: true
    title: "Hi, I'm Apurva Khatri 👋"
    subtitle: "Welcome to my Portfolio!"
    imageUrl: "/AKV2025_.png"
    imageWidth: 256
    imageHeight: 256
    imageTitle: Apurva Khatri

  analytics:
    google:
      SiteVerificationTag: "XYZabc"
    bing:
      SiteVerificationTag: "XYZabc"
    yandex:
      SiteVerificationTag: "XYZabc"

  cover:
    hidden: true
    hiddenInList: true
    hiddenInSingle: true

  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]

menu:
  main:
    - identifier: About
      name: About
      url: /about/
      weight: 10
    - identifier: Projects
      name: Projects
      url: /projects/
      weight: 20
    - identifier: Posts
      name: Posts
      url: /posts/
      weight: 30
    - identifier: Resume
      name: Resume
      url: /resume/
      weight: 40
    - identifier: Problem Solving
      name: leetcode
      url: /Leetcode/
      weight: 40
    - identifier: Fundamentals
      name: DSA
      url: /DSA/
      weight: 40

pygmentsUseClasses: true
markup:
  highlight:
    noClasses: false
  goldmark:
    renderer:
      unsafe: true
